#!/usr/bin/env python

import os
import sys

import pyarrow

from skyhookdm_singlecell.util import ArgparseBuilder

# ------------------------------
# Parse command-line arguments first
parsed_args, parsed_extra_args = (
    ArgparseBuilder.with_description('Program for inspecting data in serialized arrow files')
                   .add_input_file_arg(
                         required=True
                        ,help_str='Path to arrow file (assumed to be gene expression)'
                    )
                   .parse_args()
)

# ------------------------------
if __name__ == '__main__':
    if os.path.isfile(parsed_args.input_file):
        with open(parsed_args.input_file, 'rb') as input_handle:
            stream_reader = pyarrow.ipc.open_stream(input_handle.read())

        data_table = pyarrow.Table.from_batches(
            list(stream_reader),
            schema=stream_reader.schema
        )


        print(data_table.schema)
        print(data_table.to_pandas())
