#!/usr/bin/env python

import os
import sys
import logging

import pyarrow

from skyhookdm_singlecell.util import ArgparseBuilder
from skyhookdm_singlecell.skyhook import FormatTypes
from skyhookdm_singlecell.dataformats import SkyhookFileReader

# ------------------------------
# Parse command-line arguments first
parsed_args, parsed_extra_args = (
    ArgparseBuilder.with_description('Program for inspecting data in serialized arrow files')
                   .add_input_file_arg(
                         required=True
                        ,help_str='Path to arrow file (assumed to be gene expression)'
                    )
                   .parse_args()
)

# Bootstrap logger
logger = logging.getLogger('toolbox.run-query')
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.setLevel(logging.INFO)

# ------------------------------
if __name__ == '__main__':
    if not os.path.isfile(parsed_args.input_file):
        pass
