#!/usr/bin/env python

import os
import sys

import pyarrow

# parquet is a submodule of the pyarrow library, I think
from pyarrow import parquet

from skyhookdm_singlecell.util import ArgparseBuilder

# ------------------------------
# Parse command-line arguments first
parsed_args, parsed_extra_args = (
    ArgparseBuilder.with_description('Program for inspecting data in parquet files')
                   .add_input_file_arg(
                         required=True
                        ,help_str='Path to parquet file (assumed to be gene expression)'
                    )
                   .parse_args()
)

# ------------------------------
if __name__ == '__main__':
    if os.path.isfile(parsed_args.input_file):
        data_table = parquet.read_table(parsed_args.input_file)

        print(data_table.to_pandas())
