#!/usr/bin/env python

import os
import sys

import pyarrow

from skyhookdm_singlecell.util import ArgparseBuilder
from skyhookdm_singlecell.serialization import (SkyhookFlatbufferGeneExpression,
                                                SkyhookFlatbuffer)

# ------------------------------
# Parse command-line arguments first
parsed_args, parsed_extra_args = (
    ArgparseBuilder.with_description('Program for inspecting data in serialized arrow files')
                   .add_input_file_arg(
                         required=True
                        ,help_str='Path to arrow file (assumed to be gene expression)'
                    )
                   .parse_args()
)

# ------------------------------
if __name__ == '__main__':
    if os.path.isfile(parsed_args.input_file):
        with open(parsed_args.input_file, 'rb') as input_handle:
            skyhook_flatbuffer = SkyhookFlatbuffer.from_binary(input_handle.read())

        data_table = None

        if skyhook_flatbuffer.is_arrow_type():
            print(f'Reading {skyhook_flatbuffer.get_size()} bytes')

            data_table = skyhook_flatbuffer.get_data_as_arrow()
            print(f'Table shape: {data_table.shape}')

        print(data_table.schema)
        print(data_table.to_pandas())
